export const literalLocaleOverrides: Record<string, Record<string, string>> = {
  en: {
    '第{value}节': 'Section {value}',
    '文件#{value}': 'File #{value}',
    '未知({value})': 'Unknown ({value})',
    '错误原因={value}': 'Error reason={value}',
    '目录响应({value}个文件)': 'Directory response ({value} files)',
    '文件目录响应({value}个文件)': 'File directory response ({value} files)',
    '召唤文件目录请求({value})': 'File directory request ({value})',
    '文件段落({value}字节数据)': 'File segment ({value} bytes)',
    '文件服务附加包类型{value}': 'File service extension packet {value}',
    '(否定)': '(negative)',
    '↑上行': 'Upstream',
    '↑上行(平衡)': 'Upstream (balanced)',
    '↓下行': 'Downstream',
    '↓下行(平衡)': 'Downstream (balanced)',
    '按时间段过滤': 'Filter by time segment',
    '按时间范围查询': 'Query by time range',
    '按条数查询': 'Query by count',
    '按序号查询': 'Query by index',
    '八位位串': 'Bitstring',
    '备用': 'Reserved',
    '不可用': 'Unavailable',
    '不取消预置': 'Preset not canceled',
    '不确定': 'Indeterminate',
    '布尔': 'Boolean',
    '测试命令': 'Test command',
    '测试命令确认': 'Test command confirmation',
    '撤销': 'Cancel',
    '撤销确认': 'Cancel confirmation',
    '撤销选择': 'Cancel selection',
    '成功': 'Success',
    '成功/无后续': 'Success / no follow-up',
    '持续输出': 'Continuous output',
    '单精度浮点': 'Single-precision float',
    '当地电源合上': 'Local power on',
    '当地手动复位': 'Local manual reset',
    '定点记录': 'Fixed-point record',
    '定值修改记录': 'Setting modification record',
    '读撤销': 'Read cancel',
    '读撤销确认': 'Read cancel confirmation',
    '读请求': 'Read request',
    '读区号撤销': 'Read area cancel',
    '读区号撤销确认': 'Read area cancel confirmation',
    '读区号请求': 'Read area request',
    '读区号响应': 'Read area response',
    '读文件激活': 'Read file activation',
    '读文件激活确认': 'Read file activation confirmation',
    '读文件激活确认内容长度不足': 'Read file activation confirmation content too short',
    '读文件激活确认长度不足': 'Read file activation confirmation too short',
    '读文件激活文件名长度不足': 'Read file activation filename too short',
    '读文件激活长度不足': 'Read file activation too short',
    '读文件数据传输': 'Read file data transfer',
    '读文件数据传输确认': 'Read file data transfer confirmation',
    '读响应': 'Read response',
    '读响应(空)': 'Read response (empty)',
    '读响应(数据不足)': 'Read response (insufficient data)',
    '短脉冲': 'Short pulse',
    '短整形': 'Short integer',
    '二': 'Two',
    '发送/确认用户数据': 'Send / confirm user data',
    '发送/无回答用户数据': 'Send / no-response user data',
    '分': 'Open',
    '分(0)': 'Open (0)',
    '否定确认文件': 'Negative file confirmation',
    '否定认可(NACK)': 'Negative acknowledgement (NACK)',
    '复位进程命令': 'Reset process command',
    '复位进程确认': 'Reset process confirmation',
    '复位用户进程': 'Reset user process',
    '复位远方链路': 'Reset remote link',
    '固定帧结束字符不是16H': 'Fixed frame end character is not 16H',
    '固定帧长度不足6字节': 'Fixed frame length is less than 6 bytes',
    '固化': 'Frozen',
    '故障': 'Fault',
    '故障事件记录': 'Fault event record',
    '合': 'Close',
    '合(1)': 'Close (1)',
    '激活终止': 'Activation termination',
    '极值记录': 'Extreme value record',
    '节传输准备就绪': 'Section transfer ready',
    '节结束': 'Section end',
    '进程的总复位': 'Total process reset',
    '就绪(肯定)': 'Ready (positive)',
    '拒绝(否定)': 'Rejected (negative)',
    '可变帧第4字节不是68H': 'Variable frame 4th byte is not 68H',
    '可变帧结束字符不是16H': 'Variable frame end character is not 16H',
    '可变帧最小长度不足': 'Variable frame below minimum length',
    '可用': 'Available',
    '肯定确认节': 'Positive section confirmation',
    '肯定确认文件': 'Positive file confirmation',
    '控分': 'Open control',
    '控合': 'Close control',
    '链路测试': 'Link test',
    '链路状态/访问请求': 'Link status / access request',
    '六': 'Six',
    '录波文件': 'Disturbance record file',
    '目录查询请求': 'Directory query request',
    '目录文件名长度缺失': 'Directory filename length missing',
    '目录文件项长度不足': 'Directory file item too short',
    '目录下满足搜索时间段的文件': 'Files in directory matching the time range',
    '目录下所有文件': 'All files in directory',
    '目录项': 'Directory item',
    '目录召唤报文长度不足': 'Directory call frame too short',
    '目录召唤目录名/时间长度不足': 'Directory call directory-name/time too short',
    '目录召唤确认': 'Directory call confirmation',
    '目录召唤确认长度不足': 'Directory call confirmation too short',
    '切换撤销': 'Switch cancel',
    '切换撤销确认': 'Switch cancel confirmation',
    '切换请求': 'Switch request',
    '切换确认': 'Switch confirmation',
    '请求1级用户数据': 'Request class 1 user data',
    '请求2级用户数据': 'Request class 2 user data',
    '请求链路状态': 'Request link status',
    '请求目录': 'Request directory',
    '请求文件': 'Request file',
    '取消预置': 'Cancel preset',
    '认可(ACK)': 'Acknowledge (ACK)',
    '日': 'Day',
    '日志记录': 'Log record',
    '软压板状态错': 'Soft strap status error',
    '三': 'Three',
    '失败': 'Failed',
    '时间戳错': 'Timestamp error',
    '时钟读取': 'Clock read',
    '时钟同步命令': 'Clock sync command',
    '时钟同步确认': 'Clock sync confirmation',
    '数字签名错': 'Digital signature error',
    '双精度浮点': 'Double-precision float',
    '四': 'Four',
    '未知': 'Unknown',
    '未知错误': 'Unknown error',
    '未知公共地址': 'Unknown common address',
    '未知COT': 'Unknown COT',
    '未知IOA': 'Unknown IOA',
    '未知TI': 'Unknown TI',
    '文件': 'File',
    '文件传输': 'File transfer',
    '文件传输确认': 'File transfer confirmation',
    '文件传输准备就绪': 'File transfer ready',
    '文件结束': 'File end',
    '文件可用通知': 'File available notification',
    '文件名不支持': 'Unsupported file name',
    '文件目录召唤': 'File directory call',
    '文件数据传输确认长度不足': 'File data transfer confirmation too short',
    '文件数据传输校验码缺失': 'File data transfer checksum missing',
    '文件数据传输长度不足': 'File data transfer too short',
    '文件长度不对应': 'File length mismatch',
    '文件召唤': 'File call',
    '文件ID与激活ID不一致': 'File ID does not match activation ID',
    '无': 'None',
    '无错误': 'No error',
    '无符号短整形': 'Unsigned short integer',
    '无符号小整形': 'Unsigned small integer',
    '无符号长整形': 'Unsigned long integer',
    '无符号整形': 'Unsigned integer',
    '无附加定义': 'No additional definition',
    '无后续': 'No follow-up',
    '无请求': 'No request',
    '无时间过滤': 'No time filter',
    '无所请求的用户数据': 'No requested user data',
    '无条件传输': 'Unconditional transfer',
    '五': 'Five',
    '小整形': 'Small integer',
    '校验和错误': 'Checksum error',
    '写确认': 'Write confirmation',
    '写确认(带回显)': 'Write confirmation (echo)',
    '写文件激活': 'Write file activation',
    '写文件激活内容长度不足': 'Write file activation content too short',
    '写文件激活确认': 'Write file activation confirmation',
    '写文件激活确认内容长度不足': 'Write file activation confirmation content too short',
    '写文件激活确认长度不足': 'Write file activation confirmation too short',
    '写文件激活长度不足': 'Write file activation too short',
    '写文件数据传输': 'Write file data transfer',
    '写文件数据传输确认': 'Write file data transfer confirmation',
    '写预置': 'Write preset',
    '写预置(PI缺失)': 'Write preset (PI missing)',
    '选择': 'Select',
    '选择确认': 'Select confirmation',
    '选择文件': 'Select file',
    '遥控操作记录': 'Remote control operation record',
    '一': 'One',
    '以用户数据响应': 'Respond with user data',
    '有后续': 'Has follow-up',
    '有后续/未知错误': 'Has follow-up / unknown error',
    '有条件传输': 'Conditional transfer',
    '预置': 'Preset',
    '远方复位': 'Remote reset',
    '运行日志': 'Operation log',
    '长度超范围': 'Length out of range',
    '长脉冲': 'Long pulse',
    '长整形': 'Long integer',
    '整体(无节)': 'Whole (no section)',
    '整形': 'Integer',
    '执行': 'Execute',
    '执行结束': 'Execution end',
    '执行确认': 'Execution confirmation',
    '中间态': 'Intermediate state',
    '中止传输': 'Abort transfer',
    '字符串': 'String',
    '字符串/八位位串': 'String / bitstring',
    '自定义日志': 'Custom log',
    '总的请求电能量': 'Total energy request',
    '总请求电能量': 'Total energy call',
    '最后段(继续)': 'Last segment (continue)',
    'double(双点)': 'double (double point)',
    'float(短浮点)': 'float (short float)',
    'NVA(归一化)': 'NVA (normalized)',
    'single(单点)': 'single (single point)',
    'SOE事件记录': 'SOE event record',
    'SVA(标度化)': 'SVA (scaled)',
  },
  'zh-cn': {
    '第{value}节': '第{value}节',
    '文件#{value}': '文件#{value}',
    '未知({value})': '未知({value})',
    '错误原因={value}': '错误原因={value}',
    '目录响应({value}个文件)': '目录响应({value}个文件)',
    '文件目录响应({value}个文件)': '文件目录响应({value}个文件)',
    '召唤文件目录请求({value})': '召唤文件目录请求({value})',
    '文件段落({value}字节数据)': '文件段落({value}字节数据)',
    '文件服务附加包类型{value}': '文件服务附加包类型{value}',
    'Bitstring': '比特串',
    'Bitstring with time': '带时标比特串',
    'Clock sync': '时钟同步',
    'Directory transfer': '目录传输',
    'Double command': '双命令',
    'Double point information': '双点信息',
    'Energy call': '电能量召唤',
    'Energy float': '电能量浮点值',
    'Energy float with time': '带时标电能量浮点值',
    'File acknowledge': '文件确认',
    'File available': '文件可用',
    'File call': '文件召唤',
    'File ready': '文件就绪',
    'FIXED': '固定帧',
    'Float measurement': '浮点测量值',
    'General interrogation': '总召唤',
    'HISTORY/FIXED': '历史/固定帧',
    'Initialization end': '初始化结束',
    'Last section or segment': '最后一节或段',
    'Normalized measurement': '归一化测量值',
    'Parameter activation': '参数激活',
    'Parameter float': '浮点参数',
    'Parameter normalized': '归一化参数',
    'Parameter scaled': '标度化参数',
    'Private file service': '私有文件服务',
    'Reset process': '复位进程',
    'Scaled measurement': '标度化测量值',
    'Section ready': '节就绪',
    'Segment transfer': '段传输',
    'Single command': '单命令',
    'Single point information': '单点信息',
    'SOE double point': '双点 SOE',
    'SOE single point': '单点 SOE',
    'Test command': '测试命令',
  },
}
