export const SUPPORTED_TYPES = [
  { ti: '1', name: 'M_SP_NA_1', desc: 'Single point information', protocol: ['104', '101'] },
  { ti: '3', name: 'M_DP_NA_1', desc: 'Double point information', protocol: ['104', '101'] },
  { ti: '5', name: 'M_BO_NA_1', desc: 'Bitstring', protocol: ['104', '101'] },
  { ti: '7', name: 'M_BO_TA_1', desc: 'Bitstring with time', protocol: ['104', '101'] },
  { ti: '9', name: 'M_ME_NA_1', desc: 'Normalized measurement', protocol: ['104', '101'] },
  { ti: '11', name: 'M_ME_NB_1', desc: 'Scaled measurement', protocol: ['104', '101'] },
  { ti: '13', name: 'M_ME_NC_1', desc: 'Float measurement', protocol: ['104', '101'] },
  { ti: '30', name: 'M_SP_TB_1', desc: 'SOE single point', protocol: ['104', '101'] },
  { ti: '31', name: 'M_DP_TB_1', desc: 'SOE double point', protocol: ['104', '101'] },
  { ti: '45', name: 'C_SC_NA_1', desc: 'Single command', protocol: ['104', '101'] },
  { ti: '46', name: 'C_DC_NA_1', desc: 'Double command', protocol: ['104', '101'] },
  { ti: '70', name: 'M_EI_NA_1', desc: 'Initialization end', protocol: ['104', '101'] },
  { ti: '100', name: 'C_IC_NA_1', desc: 'General interrogation', protocol: ['104', '101'] },
  { ti: '101', name: 'C_CI_NA_1', desc: 'Energy call', protocol: ['104', '101'] },
  { ti: '103', name: 'C_CS_NA_1', desc: 'Clock sync', protocol: ['104', '101'] },
  { ti: '104', name: 'C_TS_NA_1', desc: 'Test command', protocol: ['104', '101'] },
  { ti: '105', name: 'C_RP_NA_1', desc: 'Reset process', protocol: ['104', '101'] },
  { ti: '120', name: 'F_AF_NA_1', desc: 'File available', protocol: ['104'] },
  { ti: '121', name: 'F_SC_NA_1', desc: 'File call', protocol: ['104'] },
  { ti: '122', name: 'F_DR_TA_1', desc: 'Directory transfer', protocol: ['104'] },
  { ti: '123', name: 'F_FR_NA_1', desc: 'File ready', protocol: ['104'] },
  { ti: '124', name: 'F_SR_NA_1', desc: 'Section ready', protocol: ['104'] },
  { ti: '125', name: 'F_SG_NA_1', desc: 'Segment transfer', protocol: ['104'] },
  { ti: '126', name: 'F_LS_NA_1', desc: 'Last section or segment', protocol: ['104'] },
  { ti: '127', name: 'F_FA_NA_1', desc: 'File acknowledge', protocol: ['104'] },
  { ti: '200', name: 'P_ME_NA_1', desc: 'Parameter normalized', protocol: ['104', '101'] },
  { ti: '201', name: 'P_ME_NB_1', desc: 'Parameter scaled', protocol: ['104', '101'] },
  { ti: '202', name: 'P_ME_NC_1', desc: 'Parameter float', protocol: ['104', '101'] },
  { ti: '203', name: 'P_AC_NA_1', desc: 'Parameter activation', protocol: ['104', '101'] },
  { ti: '206', name: 'M_ME_ND_1', desc: 'Energy float', protocol: ['104', '101'] },
  { ti: '207', name: 'M_ME_TD_1', desc: 'Energy float with time', protocol: ['104', '101'] },
  { ti: '210', name: 'F_XX_XX', desc: 'Private file service', protocol: ['104', '101'] },
]
